name: ❓ Question sur une tâche
description: Votre question n'est pas d'ordre technique, vous cherchez à comprendre un concept ou une consigne
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Avant de poser votre question, vérifiez que vous avez bien **lu la description de la tâche (issue)** et **essayé** d'activer le test d'acceptation. Ça aide à cibler la question.

  - type: input
    id: feature
    attributes:
      label: Tâche concernée
      description: Le nom de la feature (sous-paquet) sur laquelle vous travaillez
      placeholder: importation
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Ce que vous essayez de faire
    validations:
      required: true

  - type: textarea
    id: stuck
    attributes:
      label: Ce que vous ne comprenez pas (ou ce qui bloque)
    validations:
      required: true
